version: '3.0'
services:
  db:
    image: mysql:5.6
    ports:
      - "9999:3306"  # ports是把右边的docker容器端口映射到左边宿主机端口
      # expose的话就是暴露给 docker容器的端口 用links连接
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./db/haha:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysitedb
      - MYSQL_ROOT_PASSWORD=11111111
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: '/app/docker/start-server.sh'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db



